In [68]:
import pandas as pd

In [69]:
data = pd.read_csv("loan_approval.csv")
data = data.drop(["name","city"],axis = 1)
df = pd.DataFrame(data)
df

      income  credit_score  loan_amount  years_employed  points  loan_approved
0     113810           389        39698              27    50.0          False
1      44592           729        15446              28    55.0          False
2      33278           584        11189              13    45.0          False
3     127196           344        48823              29    50.0          False
4      66048           496        47174               4    25.0          False
...      ...           ...          ...             ...     ...            ...
1995   92163           770        12251              13    85.0           True
1996   38799           635        48259              17    40.0          False
1997   41957           763        16752               5    60.0           True
1998  139022           360        24031              35    55.0          False
1999   41188           482        31397               6    20.0          False

[2000 rows x 6 columns]

In [70]:
df.shape

(2000, 6)

In [71]:
df.columns

Index(['income', 'credit_score', 'loan_amount', 'years_employed', 'points',
       'loan_approved'],
      dtype='str')

In [72]:
df.describe()

              income  credit_score   loan_amount  years_employed       points
count    2000.000000   2000.000000   2000.000000     2000.000000  2000.000000
mean    90585.977000    573.946000  25308.503000       20.441000    56.680000
std     34487.874907    160.564945  14207.320147       11.777813    18.638033
min     30053.000000    300.000000   1022.000000        0.000000    10.000000
25%     61296.250000    433.000000  12748.750000       10.000000    45.000000
50%     90387.500000    576.000000  25661.500000       21.000000    55.000000
75%    120099.750000    715.000000  37380.500000       31.000000    70.000000
max    149964.000000    850.000000  49999.000000       40.000000   100.000000

In [73]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   income          2000 non-null   int64
 1   credit_score    2000 non-null   int64
 2   loan_amount     2000 non-null   int64
 3   years_employed  2000 non-null   int64
 4   points          2000 non-null   float64
 5   loan_approved   2000 non-null   bool
dtypes: bool(1), float64(1), int64(4)
memory usage: 80.2 KB

In [74]:
df.isna().sum()

income            0
credit_score      0
loan_amount       0
years_employed    0
points            0
loan_approved     0
dtype: int64

In [75]:
X = df.drop("loan_approved",axis = 1)
y = df["loan_approved"]
X,y

(      income  credit_score  loan_amount  years_employed  points
 0     113810           389        39698              27    50.0
 1      44592           729        15446              28    55.0
 2      33278           584        11189              13    45.0
 3     127196           344        48823              29    50.0
 4      66048           496        47174               4    25.0
 ...      ...           ...          ...             ...     ...
 1995   92163           770        12251              13    85.0
 1996   38799           635        48259              17    40.0
 1997   41957           763        16752               5    60.0
 1998  139022           360        24031              35    55.0
 1999   41188           482        31397               6    20.0

 [2000 rows x 5 columns],
 0       False
 1       False
 2       False
 3       False
 4       False
         ...
 1995     True
 1996    False
 1997     True
 1998    False
 1999    False
 Name: loan_approved, Length: 2000, dtype: bool)

In [76]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 42)

In [77]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train,X_test

(array([[ 0.64380015, -1.18010928, -1.3242847 , -1.47851122, -0.34704346],
        [ 0.38897205,  0.00991837,  0.16548855, -0.55320245, -0.34704346],
        [-0.10684367, -1.54390012, -0.33712568, -0.88967837, -0.34704346],
        ...,
        [-0.19142776,  0.0284162 , -0.61057674, -0.04848858, -0.34704346],
        [ 1.25726015, -1.12461577, -0.89557807, -0.3849645 ,  0.18424232],
        [ 0.27856785, -1.66721905,  0.39174645, -0.21672654, -0.61268635]],
       shape=(1400, 5)),
 array([[ 1.17128038, -0.78548872, -0.65458117, -0.88967837, -0.08140057],
        [-1.04552644,  1.44041792, -1.09951488,  0.0356304 ,  1.51245676],
        [ 0.45131247,  0.76216382,  0.45601701,  1.2132961 ,  0.98117099],
        ...,
        [ 0.27720125,  1.1321206 , -0.42697692,  1.12917712,  1.51245676],
        [ 0.70477397,  1.60689847,  1.22414592, -1.22615428,  1.51245676],
        [-0.68436488,  1.28010332,  0.29707669,  0.54034427,  0.7155281 ]],
       shape=(600, 5)))

In [78]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
y_pred

array([False,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True,  True, False, False,  True, False, False,
       False, False,  True, False, False, False,  True,  True,  True,
       False,  True, False, False,  True, False,  True, False, False,
       False, False, False, False, False, False, False, False,  True,
        True, False, False, False,  True,  True, False, False, False,
        True, False,  True, False, False,  True, False, False, False,
       False, False, False,  True, False,  True,  True, False, False,
        True, False,  True, False,  True,  True, False,  True,  True,
        True,  True,  True, False, False,  True,  True,  True, False,
       False,  True,  True,  True, False,  True, False,  True,  True,
        True,  True, False, False,  True, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False, False,  True,  True, False, False,  True,  True,
        True, False, False, False, False,  True, False,  True,  True,
       False, False, False, False,  True, False, False,  True, False,
       False,  True, False,  True, False, False, False, False, False,
        True,  True, False, False, False,  True, False, False,  True,
       False,  True,  True, False,  True,  True, False, False,  True,
       False, False, False,  True, False,  True,  True, False,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True,  True, False, False, False, False, False, False, False,
       False,  True,  True,  True, False,  True,  True,  True,  True,
       False, False,  True,  True, False,  True,  True, False, False,
        True, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False, False, False, False, False,  True,  True, False,
       False, False,  True,  True, False,  True, False,  True, False,
       False, False, False,  True, False, False,  True,  True, False,
        True, False, False,  True, False, False,  True, False,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
       False,  True,  True, False,  True, False, False,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
       False,  True,  True, False,  True, False, False, False, False,
       False,  True, False,  True,  True, False,  True,  True, False,
        True,  True,  True,  True, False, False,  True, False, False,
       False, False,  True, False, False, False,  True, False,  True,
       False, False, False,  True,  True,  True,  True, False, False,
        True,  True, False, False,  True,  True, False,  True,  True,
        True, False,  True, False,  True, False,  True,  True, False,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True,  True, False,  True,  True, False, False,  True,
       False, False,  True, False, False, False,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True, False,
       False,  True,  True,  True, False, False,  True, False,  True,
       False, False, False,  True, False,  True,  True, False,  True,
        True, False, False,  True, False, False, False, False, False,
       False,  True,  True, False,  True, False,  True, False, False,
       False, False, False, False, False,  True,  True, False, False,
        True, False,  True,  True,  True,  True, False,  True, False,
       False,  True, False,  True,  True,  True, False, False,  True,
       False,  True,  True, False,  True, False, False, False, False,
        True, False,  True,  True,  True, False, False, False, False,
        True, False, False,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True, False, False, False, False, False,  True,  True, False,
        True, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False, False,  True,  True,  True,
       False, False,  True,  True, False, False,  True, False,  True,
       False,  True, False, False,  True, False, False,  True,  True,
        True,  True,  True, False,  True, False,  True,  True, False,
        True, False, False,  True,  True, False, False, False,  True,
       False, False,  True,  True, False, False,  True,  True,  True,
       False, False,  True,  True, False, False,  True,  True, False,
       False,  True,  True, False,  True,  True,  True, False, False,
       False, False, False, False,  True, False,  True, False, False,
       False, False,  True,  True,  True,  True])

In [79]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred))

0.9733333333333334