In [58]:
import pandas as pd
import numpy as np

In [3]:
c_data = pd.read_csv("customers_dataset.csv")
o_data = pd.read_csv("orders_dataset.csv")

c_df = pd.DataFrame(c_data)
o_df = pd.DataFrame(o_data)

o_df

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City,Status,TotalAmount
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000
1,1002,202,Headphones,Electronics,2,2500,Thrissur,Completed,5000
2,1003,203,Office Chair,Furniture,1,8500,Kozhikode,Pending,8500
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400
4,1005,205,Desk,Furniture,1,12000,Trivandrum,Cancelled,12000
5,1006,206,Monitor,Electronics,2,14500,Kollam,Completed,29000
6,1007,207,Mouse,Electronics,4,900,Thrissur,Completed,3600
7,1008,208,Bookshelf,Furniture,1,7000,Kozhikode,Pending,7000
8,1009,209,Webcam,Electronics,2,3200,Kochi,Completed,6400
9,1010,210,Study Table,Furniture,1,9500,Kottayam,Completed,9500
10,1011,211,USB Hub,Electronics,3,1100,Kollam,Completed,3300
11,1012,212,Table Lamp,Furniture,2,1600,Trivandrum,Pending,3200
12,1013,213,Printer,Electronics,1,18500,Kochi,Completed,18500
13,1014,214,Sofa,Furniture,1,28000,Kottayam,Cancelled,28000
14,1015,215,Microphone,Electronics,2,4500,Thrissur,Completed,9000

In [4]:
o_df.head()

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City,Status,TotalAmount
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000
1,1002,202,Headphones,Electronics,2,2500,Thrissur,Completed,5000
2,1003,203,Office Chair,Furniture,1,8500,Kozhikode,Pending,8500
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400
4,1005,205,Desk,Furniture,1,12000,Trivandrum,Cancelled,12000

In [7]:
o_df.tail()
o_df.shape

(15, 9)

In [15]:
o_df.info()
o_df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OrderID      15 non-null     int64
 1   CustomerID   15 non-null     int64
 2   Product      15 non-null     str
 3   Category     15 non-null     str
 4   Quantity     15 non-null     int64
 5   UnitPrice    15 non-null     int64
 6   City         15 non-null     str
 7   Status       15 non-null     str
 8   TotalAmount  15 non-null     int64
dtypes: int64(5), str(4)
memory usage: 1.2 KB

           OrderID  CustomerID   Quantity     UnitPrice   TotalAmount
count    15.000000   15.000000  15.000000     15.000000     15.000000
mean   1008.000000  208.000000   1.800000  11906.666667  14226.666667
std       4.472136    4.472136   0.941124  16550.850935  16305.102911
min    1001.000000  201.000000   1.000000    900.000000   3200.000000
25%    1004.500000  204.500000   1.000000   2150.000000   5200.000000
50%    1008.000000  208.000000   2.000000   7000.000000   8500.000000
75%    1011.500000  211.500000   2.000000  13250.000000  15250.000000
max    1015.000000  215.000000   4.000000  65000.000000  65000.000000

In [23]:
o_df[["Product","City"]].nunique()

Product    15
City        6
dtype: int64

In [24]:
o_df.loc[o_df["Category"] == "Electronics"]

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City,Status,TotalAmount
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000
1,1002,202,Headphones,Electronics,2,2500,Thrissur,Completed,5000
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400
5,1006,206,Monitor,Electronics,2,14500,Kollam,Completed,29000
6,1007,207,Mouse,Electronics,4,900,Thrissur,Completed,3600
8,1009,209,Webcam,Electronics,2,3200,Kochi,Completed,6400
10,1011,211,USB Hub,Electronics,3,1100,Kollam,Completed,3300
12,1013,213,Printer,Electronics,1,18500,Kochi,Completed,18500
14,1015,215,Microphone,Electronics,2,4500,Thrissur,Completed,9000

In [25]:
o_df.loc[o_df["Quantity"] > 2]

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City,Status,TotalAmount
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400
6,1007,207,Mouse,Electronics,4,900,Thrissur,Completed,3600
10,1011,211,USB Hub,Electronics,3,1100,Kollam,Completed,3300

In [28]:
o_df["Status"].value_counts()

Status
Completed    10
Pending       3
Cancelled     2
Name: count, dtype: int64

In [30]:
o_df["Revenue"] = o_df["Quantity"] * o_df["UnitPrice"]
o_df[["Product","Quantity","UnitPrice","Revenue"]]

         Product  Quantity  UnitPrice  Revenue
0         Laptop         1      65000    65000
1     Headphones         2       2500     5000
2   Office Chair         1       8500     8500
3       Keyboard         3       1800     5400
4           Desk         1      12000    12000
5        Monitor         2      14500    29000
6          Mouse         4        900     3600
7      Bookshelf         1       7000     7000
8         Webcam         2       3200     6400
9    Study Table         1       9500     9500
10       USB Hub         3       1100     3300
11    Table Lamp         2       1600     3200
12       Printer         1      18500    18500
13          Sofa         1      28000    28000
14    Microphone         2       4500     9000

In [31]:
o_df["Revenue"].sum()

np.int64(213400)

In [32]:
o_df.groupby("Category")["UnitPrice"].mean()

Category
Electronics    12444.444444
Furniture      11100.000000
Name: UnitPrice, dtype: float64

In [33]:
o_df.groupby("Category")["Quantity"].sum()

Category
Electronics    20
Furniture       7
Name: Quantity, dtype: int64

In [35]:
o_df.groupby("City")["TotalAmount"].sum()

City
Kochi         95300
Kollam        32300
Kottayam      37500
Kozhikode     15500
Thrissur      17600
Trivandrum    15200
Name: TotalAmount, dtype: int64

In [36]:
o_df.groupby("Status")["TotalAmount"].mean()

Status
Cancelled    20000.000000
Completed    15470.000000
Pending       6233.333333
Name: TotalAmount, dtype: float64

In [37]:
o_df.groupby("Category")["TotalAmount"].max()

Category
Electronics    65000
Furniture      28000
Name: TotalAmount, dtype: int64

In [38]:
o_df.sort_values("TotalAmount",ascending = False)

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City,Status,TotalAmount,Revenue
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000,65000
5,1006,206,Monitor,Electronics,2,14500,Kollam,Completed,29000,29000
13,1014,214,Sofa,Furniture,1,28000,Kottayam,Cancelled,28000,28000
12,1013,213,Printer,Electronics,1,18500,Kochi,Completed,18500,18500
4,1005,205,Desk,Furniture,1,12000,Trivandrum,Cancelled,12000,12000
9,1010,210,Study Table,Furniture,1,9500,Kottayam,Completed,9500,9500
14,1015,215,Microphone,Electronics,2,4500,Thrissur,Completed,9000,9000
2,1003,203,Office Chair,Furniture,1,8500,Kozhikode,Pending,8500,8500
7,1008,208,Bookshelf,Furniture,1,7000,Kozhikode,Pending,7000,7000
8,1009,209,Webcam,Electronics,2,3200,Kochi,Completed,6400,6400
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400,5400
1,1002,202,Headphones,Electronics,2,2500,Thrissur,Completed,5000,5000
6,1007,207,Mouse,Electronics,4,900,Thrissur,Completed,3600,3600
10,1011,211,USB Hub,Electronics,3,1100,Kollam,Completed,3300,3300
11,1012,212,Table Lamp,Furniture,2,1600,Trivandrum,Pending,3200,3200

In [39]:
o_df.sort_values("TotalAmount",ascending = False).head()

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City,Status,TotalAmount,Revenue
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000,65000
5,1006,206,Monitor,Electronics,2,14500,Kollam,Completed,29000,29000
13,1014,214,Sofa,Furniture,1,28000,Kottayam,Cancelled,28000,28000
12,1013,213,Printer,Electronics,1,18500,Kochi,Completed,18500,18500
4,1005,205,Desk,Furniture,1,12000,Trivandrum,Cancelled,12000,12000

In [50]:
o_df.loc[o_df["TotalAmount"].idxmax(),"Product"]

'Laptop'

In [54]:
o_df.groupby(["City","Status"])["OrderID"].count()

City        Status
Kochi       Completed    4
Kollam      Completed    2
Kottayam    Cancelled    1
            Completed    1
Kozhikode   Pending      2
Thrissur    Completed    3
Trivandrum  Cancelled    1
            Pending      1
Name: OrderID, dtype: int64

In [55]:
o_df.loc[o_df["Status"] == "Completed"]["TotalAmount"].sum()

np.int64(154700)

In [57]:
revenue = o_df.groupby("City")["TotalAmount"].sum()
revenue[revenue > 20000]

City
Kochi       95300
Kollam      32300
Kottayam    37500
Name: TotalAmount, dtype: int64

In [60]:
o_df["PriceLevel"] = np.where(o_df["UnitPrice"] >= 10000, "High", "Normal")
o_df

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City,Status,TotalAmount,Revenue,PriceLevel
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000,65000,High
1,1002,202,Headphones,Electronics,2,2500,Thrissur,Completed,5000,5000,Normal
2,1003,203,Office Chair,Furniture,1,8500,Kozhikode,Pending,8500,8500,Normal
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400,5400,Normal
4,1005,205,Desk,Furniture,1,12000,Trivandrum,Cancelled,12000,12000,High
5,1006,206,Monitor,Electronics,2,14500,Kollam,Completed,29000,29000,High
6,1007,207,Mouse,Electronics,4,900,Thrissur,Completed,3600,3600,Normal
7,1008,208,Bookshelf,Furniture,1,7000,Kozhikode,Pending,7000,7000,Normal
8,1009,209,Webcam,Electronics,2,3200,Kochi,Completed,6400,6400,Normal
9,1010,210,Study Table,Furniture,1,9500,Kottayam,Completed,9500,9500,Normal
10,1011,211,USB Hub,Electronics,3,1100,Kollam,Completed,3300,3300,Normal
11,1012,212,Table Lamp,Furniture,2,1600,Trivandrum,Pending,3200,3200,Normal
12,1013,213,Printer,Electronics,1,18500,Kochi,Completed,18500,18500,High
13,1014,214,Sofa,Furniture,1,28000,Kottayam,Cancelled,28000,28000,High
14,1015,215,Microphone,Electronics,2,4500,Thrissur,Completed,9000,9000,Normal

In [61]:
o_df["OrderValueLevel"] = np.where(o_df["TotalAmount"] >= 15000, "Large", "Regular")
o_df

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City,Status,TotalAmount,Revenue,PriceLevel,OrderValueLevel
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000,65000,High,Large
1,1002,202,Headphones,Electronics,2,2500,Thrissur,Completed,5000,5000,Normal,Regular
2,1003,203,Office Chair,Furniture,1,8500,Kozhikode,Pending,8500,8500,Normal,Regular
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400,5400,Normal,Regular
4,1005,205,Desk,Furniture,1,12000,Trivandrum,Cancelled,12000,12000,High,Regular
5,1006,206,Monitor,Electronics,2,14500,Kollam,Completed,29000,29000,High,Large
6,1007,207,Mouse,Electronics,4,900,Thrissur,Completed,3600,3600,Normal,Regular
7,1008,208,Bookshelf,Furniture,1,7000,Kozhikode,Pending,7000,7000,Normal,Regular
8,1009,209,Webcam,Electronics,2,3200,Kochi,Completed,6400,6400,Normal,Regular
9,1010,210,Study Table,Furniture,1,9500,Kottayam,Completed,9500,9500,Normal,Regular
10,1011,211,USB Hub,Electronics,3,1100,Kollam,Completed,3300,3300,Normal,Regular
11,1012,212,Table Lamp,Furniture,2,1600,Trivandrum,Pending,3200,3200,Normal,Regular
12,1013,213,Printer,Electronics,1,18500,Kochi,Completed,18500,18500,High,Large
13,1014,214,Sofa,Furniture,1,28000,Kottayam,Cancelled,28000,28000,High,Large
14,1015,215,Microphone,Electronics,2,4500,Thrissur,Completed,9000,9000,Normal,Regular

In [65]:
# o_df.loc[o_df["Category"] == "Electronics"]["Quantity"].mean()
# o_df.loc[o_df["Category"] == "Furniture"]["Quantity"].mean()
o_df.groupby("Category")["Quantity"].mean()

Category
Electronics    2.222222
Furniture      1.166667
Name: Quantity, dtype: float64

In [67]:
o_df.groupby("Category")["TotalAmount"].max()

Category
Electronics    65000
Furniture      28000
Name: TotalAmount, dtype: int64

In [68]:
o_df.groupby("Category").agg(
    Total_Quantity=("Quantity", "sum"),
    Average_UnitPrice=("UnitPrice", "mean"),
    Total_Revenue=("TotalAmount", "sum")
)

             Total_Quantity  Average_UnitPrice  Total_Revenue
Category
Electronics              20       12444.444444         145200
Furniture                 7       11100.000000          68200

In [71]:
merged_df = pd.merge(o_df, c_df, on="CustomerID", how="inner")
merged_df

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City_x,Status,TotalAmount,Revenue,PriceLevel,OrderValueLevel,CustomerName,Age,Gender,Membership,City_y
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000,65000,High,Large,Akhil,24,Male,Gold,Kochi
1,1002,202,Headphones,Electronics,2,2500,Thrissur,Completed,5000,5000,Normal,Regular,Anjali,27,Female,Silver,Thrissur
2,1003,203,Office Chair,Furniture,1,8500,Kozhikode,Pending,8500,8500,Normal,Regular,Rahul,31,Male,Bronze,Kozhikode
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400,5400,Normal,Regular,Meera,29,Female,Gold,Kochi
4,1005,205,Desk,Furniture,1,12000,Trivandrum,Cancelled,12000,12000,High,Regular,Vishnu,35,Male,Silver,Trivandrum
5,1006,206,Monitor,Electronics,2,14500,Kollam,Completed,29000,29000,High,Large,Sneha,26,Female,Gold,Kollam
6,1007,207,Mouse,Electronics,4,900,Thrissur,Completed,3600,3600,Normal,Regular,Arjun,23,Male,Bronze,Thrissur
7,1008,208,Bookshelf,Furniture,1,7000,Kozhikode,Pending,7000,7000,Normal,Regular,Devika,32,Female,Silver,Kozhikode
8,1009,209,Webcam,Electronics,2,3200,Kochi,Completed,6400,6400,Normal,Regular,Nikhil,28,Male,Gold,Kochi
9,1010,210,Study Table,Furniture,1,9500,Kottayam,Completed,9500,9500,Normal,Regular,Athira,30,Female,Gold,Kottayam
10,1011,211,USB Hub,Electronics,3,1100,Kollam,Completed,3300,3300,Normal,Regular,Sreehari,25,Male,Silver,Kollam
11,1012,212,Table Lamp,Furniture,2,1600,Trivandrum,Pending,3200,3200,Normal,Regular,Fathima,34,Female,Bronze,Trivandrum
12,1013,213,Printer,Electronics,1,18500,Kochi,Completed,18500,18500,High,Large,Joel,29,Male,Gold,Kochi
13,1014,214,Sofa,Furniture,1,28000,Kottayam,Cancelled,28000,28000,High,Large,Gokul,36,Male,Silver,Kottayam
14,1015,215,Microphone,Electronics,2,4500,Thrissur,Completed,9000,9000,Normal,Regular,Keerthana,27,Female,Gold,Thrissur

In [73]:
merged_df[["CustomerName","Product","Quantity","TotalAmount","Membership","City_x"]]

   CustomerName       Product  Quantity  TotalAmount Membership      City_x
0         Akhil        Laptop         1        65000       Gold       Kochi
1        Anjali    Headphones         2         5000     Silver    Thrissur
2         Rahul  Office Chair         1         8500     Bronze   Kozhikode
3         Meera      Keyboard         3         5400       Gold       Kochi
4        Vishnu          Desk         1        12000     Silver  Trivandrum
5         Sneha       Monitor         2        29000       Gold      Kollam
6         Arjun         Mouse         4         3600     Bronze    Thrissur
7        Devika     Bookshelf         1         7000     Silver   Kozhikode
8        Nikhil        Webcam         2         6400       Gold       Kochi
9        Athira   Study Table         1         9500       Gold    Kottayam
10     Sreehari       USB Hub         3         3300     Silver      Kollam
11      Fathima    Table Lamp         2         3200     Bronze  Trivandrum
12         Joel       Printer         1        18500       Gold       Kochi
13        Gokul          Sofa         1        28000     Silver    Kottayam
14    Keerthana    Microphone         2         9000       Gold    Thrissur

In [74]:
merged_df.groupby("CustomerID")["TotalAmount"].sum()

CustomerID
201    65000
202     5000
203     8500
204     5400
205    12000
206    29000
207     3600
208     7000
209     6400
210     9500
211     3300
212     3200
213    18500
214    28000
215     9000
Name: TotalAmount, dtype: int64

In [75]:
merged_df.groupby("Membership")["TotalAmount"].sum()

Membership
Bronze     15300
Gold      142800
Silver     55300
Name: TotalAmount, dtype: int64

In [76]:
merged_df.groupby("Membership")["TotalAmount"].mean()

Membership
Bronze     5100.0
Gold      20400.0
Silver    11060.0
Name: TotalAmount, dtype: float64

In [77]:
merged_df.groupby("City_x")["Quantity"].sum()

City_x
Kochi         7
Kollam        5
Kottayam      2
Kozhikode     2
Thrissur      8
Trivandrum    3
Name: Quantity, dtype: int64

In [79]:
merged_df.groupby("Gender")["OrderID"].count()

Gender
Female    7
Male      8
Name: OrderID, dtype: int64

In [80]:
merged_df.groupby("Membership")["Age"].mean()

Membership
Bronze    29.333333
Gold      27.571429
Silver    31.000000
Name: Age, dtype: float64

In [86]:
merged_df.loc[merged_df["TotalAmount"].idxmax(),"CustomerName"]

'Akhil'

In [87]:
merged_df[(merged_df["Membership"] == "Gold") & (merged_df["Status"] == "Completed")]

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City_x,Status,TotalAmount,Revenue,PriceLevel,OrderValueLevel,CustomerName,Age,Gender,Membership,City_y
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000,65000,High,Large,Akhil,24,Male,Gold,Kochi
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400,5400,Normal,Regular,Meera,29,Female,Gold,Kochi
5,1006,206,Monitor,Electronics,2,14500,Kollam,Completed,29000,29000,High,Large,Sneha,26,Female,Gold,Kollam
8,1009,209,Webcam,Electronics,2,3200,Kochi,Completed,6400,6400,Normal,Regular,Nikhil,28,Male,Gold,Kochi
9,1010,210,Study Table,Furniture,1,9500,Kottayam,Completed,9500,9500,Normal,Regular,Athira,30,Female,Gold,Kottayam
12,1013,213,Printer,Electronics,1,18500,Kochi,Completed,18500,18500,High,Large,Joel,29,Male,Gold,Kochi
14,1015,215,Microphone,Electronics,2,4500,Thrissur,Completed,9000,9000,Normal,Regular,Keerthana,27,Female,Gold,Thrissur

In [89]:
merged_df[(merged_df["Membership"] == "Gold") & (merged_df["TotalAmount"] > 10000)]

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City_x,Status,TotalAmount,Revenue,PriceLevel,OrderValueLevel,CustomerName,Age,Gender,Membership,City_y
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000,65000,High,Large,Akhil,24,Male,Gold,Kochi
5,1006,206,Monitor,Electronics,2,14500,Kollam,Completed,29000,29000,High,Large,Sneha,26,Female,Gold,Kollam
12,1013,213,Printer,Electronics,1,18500,Kochi,Completed,18500,18500,High,Large,Joel,29,Male,Gold,Kochi

In [90]:
merged_df[(merged_df["Age"] > 30) & (merged_df["Status"] == "Completed")]

Empty DataFrame
Columns: [OrderID, CustomerID, Product, Category, Quantity, UnitPrice, City_x, Status, TotalAmount, Revenue, PriceLevel, OrderValueLevel, CustomerName, Age, Gender, Membership, City_y]
Index: []

In [91]:
merged_df[(merged_df["Gender"] == "Female") & (merged_df["City_x"] == "Kochi")]

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City_x,Status,TotalAmount,Revenue,PriceLevel,OrderValueLevel,CustomerName,Age,Gender,Membership,City_y
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400,5400,Normal,Regular,Meera,29,Female,Gold,Kochi

In [92]:
merged_df[(merged_df["Gender"] == "Male") & (merged_df["Product"] == "Electronics")]

Empty DataFrame
Columns: [OrderID, CustomerID, Product, Category, Quantity, UnitPrice, City_x, Status, TotalAmount, Revenue, PriceLevel, OrderValueLevel, CustomerName, Age, Gender, Membership, City_y]
Index: []

In [93]:
merged_df[(merged_df["Membership"] == "Silver") & (merged_df["Quantity"] > 1)]

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City_x,Status,TotalAmount,Revenue,PriceLevel,OrderValueLevel,CustomerName,Age,Gender,Membership,City_y
1,1002,202,Headphones,Electronics,2,2500,Thrissur,Completed,5000,5000,Normal,Regular,Anjali,27,Female,Silver,Thrissur
10,1011,211,USB Hub,Electronics,3,1100,Kollam,Completed,3300,3300,Normal,Regular,Sreehari,25,Male,Silver,Kollam

In [94]:
merged_df[(merged_df["City_x"] == "Thrissur") & (merged_df["TotalAmount"] > 5000)]

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City_x,Status,TotalAmount,Revenue,PriceLevel,OrderValueLevel,CustomerName,Age,Gender,Membership,City_y
14,1015,215,Microphone,Electronics,2,4500,Thrissur,Completed,9000,9000,Normal,Regular,Keerthana,27,Female,Gold,Thrissur

In [100]:
gold_spending = merged_df[merged_df["Membership"] == "Gold"].groupby("CustomerName")["TotalAmount"].sum()
gold_spending[gold_spending > 15000]

CustomerName
Akhil    65000
Joel     18500
Sneha    29000
Name: TotalAmount, dtype: int64

In [101]:
merged_df[merged_df["Status"] == "Completed"].groupby("Membership")["TotalAmount"].sum()

Membership
Bronze      3600
Gold      142800
Silver      8300
Name: TotalAmount, dtype: int64

In [102]:
merged_df[merged_df["Membership"] == "Gold"].groupby("City_x")["TotalAmount"].sum()

City_x
Kochi       95300
Kollam      29000
Kottayam     9500
Thrissur     9000
Name: TotalAmount, dtype: int64

In [103]:
merged_df.groupby("Gender")["TotalAmount"].mean()

Gender
Female     9728.571429
Male      18162.500000
Name: TotalAmount, dtype: float64

In [106]:
merged_df[merged_df["Status"] == "Cancelled"]["CustomerName"]

4     Vishnu
13     Gokul
Name: CustomerName, dtype: str

In [108]:
merged_df[
    (merged_df["Category"] == "Furniture") &
    (merged_df["Membership"] == "Gold")
]["CustomerName"]

9    Athira
Name: CustomerName, dtype: str

In [110]:
completed = merged_df[merged_df["Status"] == "Completed"]
completed.groupby("CustomerName")["TotalAmount"].sum().sort_values(ascending=False).head(3)

CustomerName
Akhil    65000
Sneha    29000
Joel     18500
Name: TotalAmount, dtype: int64

In [117]:
customer_summary = merged_df.groupby(["CustomerName","Membership","City_x"]).agg(
    Number_of_Orders=("CustomerID", "count"),
    Total_Quantity=("Quantity", "sum"),
    Total_Revenue=("TotalAmount", "sum")
)
customer_summary

,,,Number_of_Orders,Total_Quantity,Total_Revenue
CustomerName,Membership,City_x,,,
Akhil,Gold,Kochi,1,1,65000
Anjali,Silver,Thrissur,1,2,5000
Arjun,Bronze,Thrissur,1,4,3600
Athira,Gold,Kottayam,1,1,9500
Devika,Silver,Kozhikode,1,1,7000
Fathima,Bronze,Trivandrum,1,2,3200
Gokul,Silver,Kottayam,1,1,28000
Joel,Gold,Kochi,1,1,18500
Keerthana,Gold,Thrissur,1,2,9000
Meera,Gold,Kochi,1,3,5400
Nikhil,Gold,Kochi,1,2,6400
Rahul,Bronze,Kozhikode,1,1,8500
Sneha,Gold,Kollam,1,2,29000
Sreehari,Silver,Kollam,1,3,3300
Vishnu,Silver,Trivandrum,1,1,12000